### ISSUE TITLE
CrashReporter violates GPL

### ISSUE THREAD

**Issue by danimo** [RedisDesktop/CrashReporter#4]
Just a friendly reminder that you seem to be using code from qt-crashreporter from https://github.com/dschmidt/libcrashreporter-qt/, but stripped the GPL header. According to the GPL, you must not do that. If you use classes from a GPL'ed project, your application _has_ to be GPL as well.

At least the following files are affected

* `src/CrashReporter.cpp`
* `src/CrashReporter.h`
* `src/main.cpp`

If you can't work with the GPL as a license, please at least be so kind as to contact its authors and ask about a re-licensing. Mere attribution is not sufficent under the current original license.

Also note that the code in this repo as a whole bears no license, making it copyrighted code by default, which may not be distributed.

**Comment by uglide** [comment]
Hello @danimo 
I doesn't use classes from mentioned repo, just a few code snippets. I have left link to the original code in https://github.com/RedisDesktop/CrashReporter/blob/master/src/CrashReporter.cpp 
Also I have added GPLv2 license to this repo.

If you have any comments, please feel free to post comment on this issue. Thanks!
